-- CreateTable
CREATE TABLE `activities` (
    `id` VARCHAR(191) NOT NULL,
    `type` ENUM('NFT_CREATED', 'NFT_UPDATED', 'NFT_DELETED', 'NFT_LISTED', 'NFT_UNLISTED', 'NFT_SOLD', 'NFT_PURCHASED', 'BID_PLACED', 'BID_ACCEPTED', 'BID_REJECTED', 'NFT_FAVORITED', 'NFT_UNFAVORITED', 'PROFILE_UPDATED', 'WALLET_CONNECTED') NOT NULL,
    `description` VARCHAR(191) NOT NULL,
    `metadata` JSON NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `userId` VARCHAR(191) NOT NULL,
    `nftId` VARCHAR(191) NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `activities` ADD CONSTRAINT `activities_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `activities` ADD CONSTRAINT `activities_nftId_fkey` FOREIGN KEY (`nftId`) REFERENCES `nfts`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
